-- Fix script for user_roles table
-- Run this first to fix the table structure issue

-- Drop the table and related objects in correct order
DROP TABLE IF EXISTS public.user_role_assignments CASCADE;
DROP TABLE IF EXISTS public.user_roles CASCADE;

-- Recreate user_roles table with correct structure
CREATE TABLE IF NOT EXISTS public.user_roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    display_name text NOT NULL,
    description text,
    is_system_role boolean DEFAULT false,
    permissions jsonb DEFAULT '{}',
    created_at timestamptz DEFAULT now()
);

-- Seed system roles
INSERT INTO public.user_roles (name, display_name, description, is_system_role) VALUES
    ('School Administration', 'School Administration', 'Govern institutional operations, multi-branch strategy, and global oversight', true),
    ('Branch Admin', 'Branch Admin', 'Manage specific branch operations and staff', true),
    ('Principal', 'Principal / Director', 'Lead academic excellence and oversee institutional growth', true),
    ('HR Manager', 'HR Management', 'Manage human capital, recruitment, and organizational compliance', true),
    ('Academic Coordinator', 'Academic Coordinator', 'Synchronize curriculum delivery and maintain pedagogical standards', true),
    ('Accountant', 'Financial Controller', 'Oversee fiscal health, fee collections, and institutional financial reporting', true),
    ('Teacher', 'Faculty Member', 'Empower students, manage classrooms, and curate learning experiences', true),
    ('Student', 'Student Portal', 'Access academic timeline, assignments, and digital learning resources', true),
    ('Parent/Guardian', 'Parent / Guardian', 'Partner in child''s educational journey and manage family needs', true),
    ('Transport Staff', 'Transport Operations', 'Manage logistical operations, routes, and student transit safety', true),
    ('E-commerce Operator', 'E-commerce Operator', 'Administer institutional storefront, inventory, and supply chain', true),
    ('Super Admin', 'Super Admin', 'System-wide administrative access', true),
    ('Minimal Admin', 'Minimal Admin', 'Limited administrative access for setup', true)
ON CONFLICT (name) DO NOTHING;

-- Recreate user_role_assignments table
CREATE TABLE IF NOT EXISTS public.user_role_assignments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    role_name text NOT NULL REFERENCES public.user_roles(name) ON DELETE CASCADE,
    assigned_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    branch_id bigint REFERENCES public.school_branches(id) ON DELETE CASCADE,
    assigned_at timestamptz DEFAULT now(),
    UNIQUE(user_id, role_name, branch_id)
);

-- Add RLS policies
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users can view user roles" ON public.user_roles FOR SELECT USING (auth.uid() IS NOT NULL);

ALTER TABLE public.user_role_assignments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view their own role assignments" ON public.user_role_assignments;
CREATE POLICY "Users can view their own role assignments" ON public.user_role_assignments FOR SELECT USING (user_id = auth.uid());

SELECT 'user_roles table fixed successfully!' as result;
